export const GET_SIGN_UP_DATA= 'GET_SIGN_UP_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';
export const GET_CURRENT_LOCACTION = 'GET_CURRENT_LOCACTION';
